# Generated by Django 4.2.7 on 2026-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="playlist_serve_mode",
            field=models.CharField(
                choices=[
                    ("download", "Download Videos"),
                    ("direct", "Direct Stream (No Download)"),
                ],
                default="download",
                help_text="How to serve playlist videos: download or direct stream",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_source",
            field=models.CharField(
                choices=[
                    ("media_files", "Media Files"),
                    ("playlist", "YouTube Playlist"),
                    ("playlist_direct", "YouTube Playlist (Direct Stream)"),
                ],
                default="media_files",
                max_length=20,
            ),
        ),
    ]
